spring:
  application:
    name: health_management_app
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=10m,maximumSize=500
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:4b

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
